# Generated by Django 3.1.7 on 2021-03-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activism_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='code',
            field=models.CharField(default='invalid', max_length=24),
            preserve_default=False,
        ),
    ]
